package dev.takesome.htmldom.desktop;

import java.awt.Color;
import java.util.Locale;
import java.util.Map;

/** CSS named-color registry shared by desktop paint engines. */
final class HtmlDomNamedColors {
        private static final Map<String, Color> NAMED_COLORS = Map.ofEntries(
            Map.entry("aliceblue", new Color(0xF0F8FF)),
            Map.entry("antiquewhite", new Color(0xFAEBD7)),
            Map.entry("aqua", new Color(0x00FFFF)),
            Map.entry("aquamarine", new Color(0x7FFFD4)),
            Map.entry("azure", new Color(0xF0FFFF)),
            Map.entry("beige", new Color(0xF5F5DC)),
            Map.entry("bisque", new Color(0xFFE4C4)),
            Map.entry("black", new Color(0x000000)),
            Map.entry("blanchedalmond", new Color(0xFFEBCD)),
            Map.entry("blue", new Color(0x0000FF)),
            Map.entry("blueviolet", new Color(0x8A2BE2)),
            Map.entry("brown", new Color(0xA52A2A)),
            Map.entry("burlywood", new Color(0xDEB887)),
            Map.entry("cadetblue", new Color(0x5F9EA0)),
            Map.entry("chartreuse", new Color(0x7FFF00)),
            Map.entry("chocolate", new Color(0xD2691E)),
            Map.entry("coral", new Color(0xFF7F50)),
            Map.entry("cornflowerblue", new Color(0x6495ED)),
            Map.entry("cornsilk", new Color(0xFFF8DC)),
            Map.entry("crimson", new Color(0xDC143C)),
            Map.entry("cyan", new Color(0x00FFFF)),
            Map.entry("darkblue", new Color(0x00008B)),
            Map.entry("darkcyan", new Color(0x008B8B)),
            Map.entry("darkgoldenrod", new Color(0xB8860B)),
            Map.entry("darkgray", new Color(0xA9A9A9)),
            Map.entry("darkgreen", new Color(0x006400)),
            Map.entry("darkgrey", new Color(0xA9A9A9)),
            Map.entry("darkkhaki", new Color(0xBDB76B)),
            Map.entry("darkmagenta", new Color(0x8B008B)),
            Map.entry("darkolivegreen", new Color(0x556B2F)),
            Map.entry("darkorange", new Color(0xFF8C00)),
            Map.entry("darkorchid", new Color(0x9932CC)),
            Map.entry("darkred", new Color(0x8B0000)),
            Map.entry("darksalmon", new Color(0xE9967A)),
            Map.entry("darkseagreen", new Color(0x8FBC8F)),
            Map.entry("darkslateblue", new Color(0x483D8B)),
            Map.entry("darkslategray", new Color(0x2F4F4F)),
            Map.entry("darkslategrey", new Color(0x2F4F4F)),
            Map.entry("darkturquoise", new Color(0x00CED1)),
            Map.entry("darkviolet", new Color(0x9400D3)),
            Map.entry("deeppink", new Color(0xFF1493)),
            Map.entry("deepskyblue", new Color(0x00BFFF)),
            Map.entry("dimgray", new Color(0x696969)),
            Map.entry("dimgrey", new Color(0x696969)),
            Map.entry("dodgerblue", new Color(0x1E90FF)),
            Map.entry("firebrick", new Color(0xB22222)),
            Map.entry("floralwhite", new Color(0xFFFAF0)),
            Map.entry("forestgreen", new Color(0x228B22)),
            Map.entry("fuchsia", new Color(0xFF00FF)),
            Map.entry("gainsboro", new Color(0xDCDCDC)),
            Map.entry("ghostwhite", new Color(0xF8F8FF)),
            Map.entry("gold", new Color(0xFFD700)),
            Map.entry("goldenrod", new Color(0xDAA520)),
            Map.entry("gray", new Color(0x808080)),
            Map.entry("green", new Color(0x008000)),
            Map.entry("greenyellow", new Color(0xADFF2F)),
            Map.entry("grey", new Color(0x808080)),
            Map.entry("honeydew", new Color(0xF0FFF0)),
            Map.entry("hotpink", new Color(0xFF69B4)),
            Map.entry("indianred", new Color(0xCD5C5C)),
            Map.entry("indigo", new Color(0x4B0082)),
            Map.entry("ivory", new Color(0xFFFFF0)),
            Map.entry("khaki", new Color(0xF0E68C)),
            Map.entry("lavender", new Color(0xE6E6FA)),
            Map.entry("lavenderblush", new Color(0xFFF0F5)),
            Map.entry("lawngreen", new Color(0x7CFC00)),
            Map.entry("lemonchiffon", new Color(0xFFFACD)),
            Map.entry("lightblue", new Color(0xADD8E6)),
            Map.entry("lightcoral", new Color(0xF08080)),
            Map.entry("lightcyan", new Color(0xE0FFFF)),
            Map.entry("lightgoldenrodyellow", new Color(0xFAFAD2)),
            Map.entry("lightgray", new Color(0xD3D3D3)),
            Map.entry("lightgreen", new Color(0x90EE90)),
            Map.entry("lightgrey", new Color(0xD3D3D3)),
            Map.entry("lightpink", new Color(0xFFB6C1)),
            Map.entry("lightsalmon", new Color(0xFFA07A)),
            Map.entry("lightseagreen", new Color(0x20B2AA)),
            Map.entry("lightskyblue", new Color(0x87CEFA)),
            Map.entry("lightslategray", new Color(0x778899)),
            Map.entry("lightslategrey", new Color(0x778899)),
            Map.entry("lightsteelblue", new Color(0xB0C4DE)),
            Map.entry("lightyellow", new Color(0xFFFFE0)),
            Map.entry("lime", new Color(0x00FF00)),
            Map.entry("limegreen", new Color(0x32CD32)),
            Map.entry("linen", new Color(0xFAF0E6)),
            Map.entry("magenta", new Color(0xFF00FF)),
            Map.entry("maroon", new Color(0x800000)),
            Map.entry("mediumaquamarine", new Color(0x66CDAA)),
            Map.entry("mediumblue", new Color(0x0000CD)),
            Map.entry("mediumorchid", new Color(0xBA55D3)),
            Map.entry("mediumpurple", new Color(0x9370DB)),
            Map.entry("mediumseagreen", new Color(0x3CB371)),
            Map.entry("mediumslateblue", new Color(0x7B68EE)),
            Map.entry("mediumspringgreen", new Color(0x00FA9A)),
            Map.entry("mediumturquoise", new Color(0x48D1CC)),
            Map.entry("mediumvioletred", new Color(0xC71585)),
            Map.entry("midnightblue", new Color(0x191970)),
            Map.entry("mintcream", new Color(0xF5FFFA)),
            Map.entry("mistyrose", new Color(0xFFE4E1)),
            Map.entry("moccasin", new Color(0xFFE4B5)),
            Map.entry("navajowhite", new Color(0xFFDEAD)),
            Map.entry("navy", new Color(0x000080)),
            Map.entry("oldlace", new Color(0xFDF5E6)),
            Map.entry("olive", new Color(0x808000)),
            Map.entry("olivedrab", new Color(0x6B8E23)),
            Map.entry("orange", new Color(0xFFA500)),
            Map.entry("orangered", new Color(0xFF4500)),
            Map.entry("orchid", new Color(0xDA70D6)),
            Map.entry("palegoldenrod", new Color(0xEEE8AA)),
            Map.entry("palegreen", new Color(0x98FB98)),
            Map.entry("paleturquoise", new Color(0xAFEEEE)),
            Map.entry("palevioletred", new Color(0xDB7093)),
            Map.entry("papayawhip", new Color(0xFFEFD5)),
            Map.entry("peachpuff", new Color(0xFFDAB9)),
            Map.entry("peru", new Color(0xCD853F)),
            Map.entry("pink", new Color(0xFFC0CB)),
            Map.entry("plum", new Color(0xDDA0DD)),
            Map.entry("powderblue", new Color(0xB0E0E6)),
            Map.entry("purple", new Color(0x800080)),
            Map.entry("rebeccapurple", new Color(0x663399)),
            Map.entry("red", new Color(0xFF0000)),
            Map.entry("rosybrown", new Color(0xBC8F8F)),
            Map.entry("royalblue", new Color(0x4169E1)),
            Map.entry("saddlebrown", new Color(0x8B4513)),
            Map.entry("salmon", new Color(0xFA8072)),
            Map.entry("sandybrown", new Color(0xF4A460)),
            Map.entry("seagreen", new Color(0x2E8B57)),
            Map.entry("seashell", new Color(0xFFF5EE)),
            Map.entry("sienna", new Color(0xA0522D)),
            Map.entry("silver", new Color(0xC0C0C0)),
            Map.entry("skyblue", new Color(0x87CEEB)),
            Map.entry("slateblue", new Color(0x6A5ACD)),
            Map.entry("slategray", new Color(0x708090)),
            Map.entry("slategrey", new Color(0x708090)),
            Map.entry("snow", new Color(0xFFFAFA)),
            Map.entry("springgreen", new Color(0x00FF7F)),
            Map.entry("steelblue", new Color(0x4682B4)),
            Map.entry("tan", new Color(0xD2B48C)),
            Map.entry("teal", new Color(0x008080)),
            Map.entry("thistle", new Color(0xD8BFD8)),
            Map.entry("tomato", new Color(0xFF6347)),
            Map.entry("turquoise", new Color(0x40E0D0)),
            Map.entry("violet", new Color(0xEE82EE)),
            Map.entry("wheat", new Color(0xF5DEB3)),
            Map.entry("white", new Color(0xFFFFFF)),
            Map.entry("whitesmoke", new Color(0xF5F5F5)),
            Map.entry("yellow", new Color(0xFFFF00)),
            Map.entry("yellowgreen", new Color(0x9ACD32))
    );

    private HtmlDomNamedColors() {
    }

    static Color lookup(String raw) {
        if (raw == null || raw.isBlank()) return null;
        return NAMED_COLORS.get(raw.trim().toLowerCase(Locale.ROOT));
    }
}
